### ISSUE TITLE
would you help me solving Q382?

### ISSUE THREAD

**Issue by lypro09539** [algorhythms/LeetCode#9]
my code is as below：

        n = 0
        while self.head:
            if random.randint(0,n)==0:
                res = self.head.val
            n += 1
            self.head = self.head.next
        return res

yes，for test  ["Solution","getRandom","getRandom","getRandom"]
                      [[[3]],[],[],[]]
it raised UnboundLocalError: local variable 'res' referenced before assignment

but, if I name new var to make it equal to self.head:  ss = self.head ,    AC!!!!! 

        n = 0
        ss = self.head
        while ss:
            if random.randint(0,n)==0:
                res = ss.val
            n += 1
            ss.head = ss.next
        return res

 I am so confused!

**Comment by iFun** [comment]
@lypro09539 if ur res does not go into if statement then return res will cause an error

define res before the while loop so that it won't cause this issue

**Comment by lypro09539** [comment]
3Q
